"""Pack the MuseScore Drumline solo-snare takes into assets/audio/marching-snare.js.

Run once by hand; the output is committed and nothing in the build calls this.
Needs Python 3 with numpy and soundfile (pip install numpy soundfile), and a
checkout of https://github.com/musescore/mdl:

    python3 tools/pack-marching-snare.py path/to/mdl

The takes are MDL's own (CC0, see assets/audio/LICENSE-marching-snare.txt). What
this does to them, and nothing more:
  - trims the silent tail once a take stays 60 dB under its peak, with a short
    fade so the cut is not a click, and trims anything before the stick lands;
  - applies MDL's own balance from MDL_Snare.sfz (group_volume + region volume),
    so a hit and a buzz sit where Christian Collins put them;
  - scales every take by one shared factor so the loudest peaks just under full
    scale, and records that factor as `gain` so the page can restore it;
  - stores 16-bit mono PCM as base64 inside a classic script, which a page opened
    from disk can load (a fetch of a .wav cannot) and which needs no decoder.
"""
import base64
import pathlib
import sys

import numpy as np
import soundfile as sf

RATE = 44100
# name -> (MDL files, dB per take from MDL_Snare.sfz: group_volume + region volume)
SETS = {
    "hit": (["hit_1", "hit_2", "hit_3", "hit_4"], [0, 0, 0, 3]),
    "crush": (["crush_short_1", "crush_short_2", "crush_short_3", "crush_short_4"], [2, 2, 2, 2]),
    "crushLong": (["crush_long_1", "crush_long_2", "crush_long_3", "crush_long_4"],
                  [1.5 + 2, 1.5 + 2, 1.5, 1.5 + 5]),
}
FLOOR_DB = -60
FADE_S = 0.02


def trimmed(x):
    peak = np.abs(x).max()
    onset = int(np.argmax(np.abs(x) > peak * 0.05))
    start = max(0, onset - int(RATE * 0.0003))
    loud = np.where(np.abs(x) > peak * 10 ** (FLOOR_DB / 20))[0]
    end = min(len(x), loud[-1] + int(RATE * FADE_S))
    y = x[start:end].copy()
    n = int(RATE * FADE_S)
    y[-n:] *= 0.5 * (1 + np.cos(np.linspace(0, np.pi, n)))
    return y


def main(mdl):
    src = pathlib.Path(mdl) / "resources/sound/MDL_samples/snare"
    takes = {}
    for key, (names, dbs) in SETS.items():
        takes[key] = []
        for name, db in zip(names, dbs):
            x, rate = sf.read(src / f"{name}.ogg", dtype="float64")
            assert rate == RATE and x.ndim == 1, name
            takes[key].append(trimmed(x) * 10 ** (db / 20))
    loudest = max(np.abs(t).max() for ts in takes.values() for t in ts)
    scale = 0.98 / loudest

    lines = []
    total = 0
    for key, ts in takes.items():
        encoded = []
        for t in ts:
            pcm = np.clip(np.round(t * scale * 32767), -32768, 32767).astype("<i2").tobytes()
            total += len(pcm)
            encoded.append('      "' + base64.b64encode(pcm).decode("ascii") + '"')
        lines.append(f"    {key}: [\n" + ",\n".join(encoded) + "\n    ],")

    out = pathlib.Path(__file__).resolve().parent.parent / "assets/audio/marching-snare.js"
    out.write_text(
        "/* GENERATED by tools/pack-marching-snare.py — do not edit by hand.\n"
        "   Marching snare takes from MuseScore Drumline (MDL), solo snare, CC0 1.0:\n"
        "   hit_1-4, crush_short_1-4 and crush_long_1-4 from\n"
        "   https://github.com/musescore/mdl resources/sound/MDL_samples/snare.\n"
        "   See assets/audio/LICENSE-marching-snare.txt for the credit and waiver.\n"
        "   Each take is mono 16-bit little-endian PCM at `rate`, base64; multiply by\n"
        "   `gain` to restore MDL's level. A crush is MDL's buzz stroke. */\n"
        "(function (root) {\n"
        '  "use strict";\n'
        "  var MARCHING_SNARE = {\n"
        f"    rate: {RATE},\n"
        f"    gain: {1 / scale:.4f},\n"
        + "\n".join(lines) + "\n"
        "  };\n"
        '  if (typeof module === "object" && module.exports) module.exports = MARCHING_SNARE;\n'
        "  else root.RudimentMarchingSnare = MARCHING_SNARE;\n"
        '})(typeof self !== "undefined" ? self : this);\n',
        encoding="utf-8",
    )
    for key, ts in takes.items():
        print(key, [f"{len(t) / RATE:.3f}s" for t in ts])
    print(f"gain {1 / scale:.4f}, PCM {total / 1024:.0f} KiB, file {out.stat().st_size / 1024:.0f} KiB")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "mdl")
